sudo -u postgres psql << EOF
GRANT ALL PRIVILEGES ON DATABASE sorukayisi_db TO sorukayisi;
\c sorukayisi_db
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sorukayisi;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sorukayisi;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO sorukayisi;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO sorukayisi;
EOF